### ISSUE TITLE
Changelog is not updating when pushed  changes to git repository server

### ISSUE THREAD

**Issue by parvezq** [MartinSeeler/auto-changelog-hook#2]
I have used the script at two places.
1. Local git repository with no remote server attached. The changelog file is generating as expected.
2. Added the script to the .git/hooks directory in a remote repository on linux machine.

In case 2: I am not able to see the changelog getting updated when the associated content is cloned on multiple client machines and made changes to the project with a subsequent commit & push. The server git repository is created using git init --bare command.
Am I missing something ?

**Comment by MartinSeeler** [comment]
Thanks for your issue.
Since the remote repository is a bare repository, there are no files at all, just blobs. So the process of generating the CHANGELOG.md file should fail on remote.
Sadly, there is no way to share hooks with everyone cloning the repository. The only way is to let everyone install it localy into the checked out repository .git/hooks folder.
